# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: playwright-py

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Build project dependencies
      run: |
        python -m pip install --upgrade pip
        python3 --version
        pip install pipenv
        pipenv install
        export VENV_HOME_DIR=$(pipenv --venv)
        source $VENV_HOME_DIR/bin/activate
        export PYTHONPATH="$PYTHONPATH:."
        python -c "import sys;print(sys.path)"
        python -m playwright install
#
#    - name: Node
#      uses: actions/setup-node@v1
#      with:
#        node-version: 12.x
    - name: Test
      run: |
        ls -ll
        pipenv run pytest --alluredir=./allure-results

    - name: Create Report
      steps:
      - uses: actions/frankescobar/allure-docker-service@v1
      - run: allure generate allure-results --clean -o allure-report
      - uses: actions/upload-artifact@v1
       if: always()
       with:
        name: allure-report
        path: ./allure-report
