# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: playwright-py

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Build project dependencies
      run: |
        python -m pip install --upgrade pip
        python3 --version
        pip install pipenv
        pipenv install
        export VENV_HOME_DIR=$(pipenv --venv)
        source $VENV_HOME_DIR/bin/activate
        export PYTHONPATH="$PYTHONPATH:."
        python -c "import sys;print(sys.path)"
        python -m playwright install
        apt-get update && apt-get install -y wget default-jdk && cd /opt && \
        (wget -c https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.7.0/allure-2.7.0.tgz -O - | tar -xz && chmod +x allure-2.7.0/bin/allure)
        export PATH="${PATH}:/opt/allure-2.7.0/bin"
        allure --version


    - name: Test
      run: |
        ls -l
        pipenv run pytest --alluredir=./allure-results

    - name: Create Report
      run: |
        ls -l
        allure generate allure-results --clean -o allure-report
    - uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: ./build/reports/allure-report/

#    - name: Create Report
#      if: always()
#      container:
#        image: frankescobar/allure-docker-service
##      uses: docker://foundeo/minibox:latest
#      # trying to save history of previous runs if it is exists
#      run: allure generate allure-results --clean -o allure-report
#    - uses: actions/upload-artifact@v1
#      if: always()
#      with:
#        name: allure-report
#        path: ./allure-report