# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: playwright-py

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Build project dependencies
      run: |
        python -m pip install --upgrade pip
        python3 --version
        pip install pipenv
        pipenv install
        export VENV_HOME_DIR=$(pipenv --venv)
        source $VENV_HOME_DIR/bin/activate
        export PYTHONPATH="$PYTHONPATH:."
        python -c "import sys;print(sys.path)"
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: 'install:linux:dep'
      run: >
        sudo apt-get update
        sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0
            libgdk-pixbuf2.0-0 libegl1 libgles2 libevent-2.1-6 libnotify4 libxslt1.1
        sudo apt-get install xvfb
    - name: Test
      run: |
        ls -ll
        pipenv run pytest